name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Core RDP Settings
        run: |
          # เปิด Remote Desktop และตั้งค่า firewall
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                             -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "SecurityLayer" -Value 0 -Force

          # เปิดพอร์ต 3389
          netsh advfirewall firewall delete rule name="RDP-KHUNASIN"
          netsh advfirewall firewall add rule name="RDP-KHUNASIN" dir=in action=allow protocol=TCP localport=3389

          # รีสตาร์ท Remote Desktop service
          Restart-Service -Name TermService -Force

      - name: Create or Verify RDP User
        run: |
          $username = "KHUNASIN"
          $passwordPlain = "0932946455"
          $securePass = ConvertTo-SecureString $passwordPlain -AsPlainText -Force

          # ตรวจสอบว่ามี user อยู่หรือไม่
          $user = Get-LocalUser -Name $username -ErrorAction SilentlyContinue

          if (-not $user) {
              Write-Host "Creating user $username..."
              New-LocalUser -Name $username -Password $securePass -AccountNeverExpires
          } else {
              Write-Host "User $username already exists."
          }

          # เพิ่มเข้า group
          Add-LocalGroupMember -Group "Administrators" -Member $username
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username

          # เก็บ creds
          echo "RDP_CREDS=User: $username | Password: $passwordPlain" >> $env:GITHUB_ENV

      - name: Install Tailscale
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          Remove-Item $installerPath -Force

      - name: Connect Tailscale
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=KHUNASIN
          
          # รอ IP
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 10) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              Start-Sleep -Seconds 5
              $retries++
          }
          if (-not $tsIP) {
              Write-Error "Tailscale IP not assigned. Exiting."
              exit 1
          }
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV

      - name: Verify RDP
        run: |
          Write-Host "Tailscale IP: $env:TAILSCALE_IP"
          $testResult = Test-NetConnection -ComputerName $env:TAILSCALE_IP -Port 3389
          if (-not $testResult.TcpTestSucceeded) {
              Write-Error "TCP connection to RDP port 3389 failed"
              exit 1
          }
          Write-Host "TCP connectivity successful!"

      - name: Maintain RDP Access
        run: |
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Address: $env:TAILSCALE_IP"
          Write-Host "Username: KHUNASIN"
          Write-Host "Password: 0932946455"
          Write-Host "==================`n"
          
          # Loop ต่อเนื่องเพื่อให้ workflow active
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active - Use Ctrl+C to stop workflow"
              Start-Sleep -Seconds 300
          }
