# ==============================
# Setup RDP + Tailscale VPS ตลอดชีวิต
# ==============================

# --- 1. เปิด Remote Desktop และปรับ Security ---
Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
    -Name "fDenyTSConnections" -Value 0 -Force
Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
    -Name "UserAuthentication" -Value 0 -Force
Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
    -Name "SecurityLayer" -Value 0 -Force

# ตั้ง firewall ให้เข้าถึง port 3389
netsh advfirewall firewall delete rule name="RDP-Zezer" 2>$null
netsh advfirewall firewall add rule name="RDP-Zezer" dir=in action=allow protocol=TCP localport=3389

# ตั้งให้ TermService (RDP Service) เริ่มอัตโนมัติ
Set-Service -Name TermService -StartupType Automatic
Start-Service -Name TermService

# --- 2. สร้าง user Zezer ---
$securePass = ConvertTo-SecureString "GGG" -AsPlainText -Force
if (-not (Get-LocalUser -Name "Zezer" -ErrorAction SilentlyContinue)) {
    New-LocalUser -Name "Zezer" -Password $securePass -AccountNeverExpires
    Add-LocalGroupMember -Group "Administrators" -Member "Zezer"
    Add-LocalGroupMember -Group "Remote Desktop Users" -Member "Zezer"
}

# --- 3. ติดตั้ง Tailscale ---
$tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
$installerPath = "$env:TEMP\tailscale.msi"

Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
Remove-Item $installerPath -Force

# --- 4. เชื่อมต่อ Tailscale (Auto Start Service) ---
$authKey = "<YOUR_TAILSCALE_AUTH_KEY>"  # เปลี่ยนเป็น Auth Key ของคุณ
& "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=$authKey --hostname=VPS-Zezer --accept-routes --accept-dns

# ตั้งให้ Tailscale run เป็น service อัตโนมัติ
Start-Process "$env:ProgramFiles\Tailscale\tailscaled.exe" -ArgumentList "--service" -NoNewWindow

# --- 5. แสดง IP สำหรับ RDP ---
$tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
Write-Host "=== RDP ACCESS ==="
Write-Host "Tailscale IP: $tsIP"
Write-Host "Username: Zezer"
Write-Host "Password: GGG"
Write-Host "==================`n"

# --- 6. รักษา RDP ตลอดเวลา ---
Write-Host "RDP และ Tailscale พร้อมใช้งานตลอดชีวิต (จนกว่า VPS จะปิด)"
while ($true) {
    # ตรวจสอบว่า TermService ยังรันอยู่
    if ((Get-Service TermService).Status -ne 'Running') {
        Start-Service TermService
    }
    # ตรวจสอบว่า Tailscale ยังเชื่อมต่ออยู่
    $tsStatus = & "$env:ProgramFiles\Tailscale\tailscale.exe" status
    if ($tsStatus -notmatch "Logged in") {
        & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=$authKey --hostname=VPS-Zezer --accept-routes --accept-dns
    }
    Start-Sleep -Seconds 300
}
